# 6shapes.py
import turtle
import random
screen = turtle.Screen()
screen.title("Pixel, Line, Rectangle, Circle, Arc, and Sector Plotting with Turtle")
screen.bgcolor("white")
pen = turtle.Turtle()
pen.hideturtle()
pen.speed(0)  
def plot_pixel(x, y, color="black"):
    pen.penup()
    pen.goto(x, y)
    pen.dot(5, color)
    pen.penup()
def draw_line(x1, y1, x2, y2, color="black"):
    pen.penup()
    pen.goto(x1, y1)
    pen.pendown()
    pen.pencolor(color)
    pen.pensize(3)
    pen.goto(x2, y2)
    pen.penup()
def draw_rectangle(x, y, width, height, color="black"):
    pen.penup()
    pen.goto(x, y)
    pen.pendown()
    pen.pencolor(color)
    pen.pensize(3)
    for _ in range(2):
        pen.forward(width)
        pen.right(90)
        pen.forward(height)
        pen.right(90)
    pen.penup()
def draw_circle(x, y, radius, color="black"):
    pen.penup()
    pen.goto(x, y - radius)
    pen.pendown()
    pen.pencolor(color)
    pen.pensize(3)
    pen.circle(radius)
    pen.penup()
def draw_arc(x, y, radius, extent, color="black"):
    pen.penup()
    pen.goto(x, y - radius)
    pen.setheading(0)
    pen.pendown()
    pen.pencolor(color)
    pen.pensize(3)
    pen.circle(radius, extent)
    pen.penup()
def draw_sector(x, y, radius, angle, color="black"):
    pen.penup()
    pen.goto(x, y)
    pen.setheading(0)
    pen.pendown()
    pen.fillcolor(color)
    pen.begin_fill()
    pen.forward(radius)
    pen.left(90)
    pen.circle(radius, angle)
    pen.left(90)
    pen.forward(radius)
    pen.end_fill()
    pen.penup()
def label_shape(x, y, text, offset_x=0, offset_y=0):
    pen.penup()
    pen.goto(x + offset_x, y + offset_y)
    pen.write(text, align="center", font=("Arial", 12, "bold"))
    pen.penup()
for _ in range(4):
    x = random.randint(-300, -100)  
    y = random.randint(100, 300)
    plot_pixel(x, y, random.choice(["blue", "red", "green", "purple", "orange"]))
label_shape(-150, 300, "Pixel", offset_x=10, offset_y=-20) 
draw_line(-300, -100, -100, -200, "black")  
label_shape(-200, -180, "Line", offset_x=20, offset_y=-20) 
draw_rectangle(100, 100, 200, 100, "black")  
label_shape(200, 50, "Rectangle") 
draw_circle(200, -150, 100, "black")  
label_shape(200, -150, "Circle") 
draw_arc(0, 200, 100, 90, "black")  
label_shape(70, 170, "Arc") 
draw_sector(-100, 0, 100, 60, "grey")  
label_shape(-100, -40, "Sector") 
screen.exitonclick()
