import turtle
screen = turtle.Screen()
screen.title("Drawing Hut and Concentric Circles")
screen.bgcolor("white")
pen = turtle.Turtle()
pen.speed(5) 
pen.hideturtle()
def draw_concentric_circles(x, y, radii, color="black"):
    for radius in radii:
        pen.penup()
        pen.goto(x, y - radius)
        pen.pendown()
        pen.pencolor(color)
        pen.pensize(3)
        pen.circle(radius)
        pen.penup()
def draw_hut(x, y, length, width):
    pen.penup()
    pen.goto(x - length / 2, y + width / 2)
    pen.pendown()
    pen.pensize(3)
    pen.pencolor("black")
    for _ in range(2):
        pen.forward(length)
        pen.right(90)
        pen.forward(width)
        pen.right(90)
    pen.goto(x - length / 2, y + width / 2)
    pen.forward(length / 2)
    pen.right(240)
    pen.forward(width)
    pen.right(240)
    pen.forward(length / 2)
    pen.penup()
    pen.goto(x + length / 2, y + width / 2)
    pen.pendown()
    pen.left(240)
    pen.forward(length / 2)
    pen.left(120)
    pen.forward(width)
    pen.right(120)
    pen.forward(width)
    pen.right(120)
    pen.forward(length / 2)
    pen.penup()
def label_shape(x, y, text, offset_x=0, offset_y=0):
    pen.penup()
    pen.goto(x + offset_x, y + offset_y)
    pen.write(text, align="center", font=("Arial", 12, "bold"))
    pen.penup()
draw_concentric_circles(-150, -100, [50, 25], "black")
label_shape(-150, -160, "Concentric Circles", offset_x=0, offset_y=-10)
draw_hut(150, 100, 100, 50)
label_shape(150, 50, "Hut", offset_x=0, offset_y=-20)
screen.exitonclick()
